---
title: "Entrega-1"
output: html_document
date: '2023-02-20'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

## R Markdown

### Transformació de les dades

#### Edat: 
Quatre possibles categories: [0,25] [26-45] [46-65] [66-inf]
  
#### Job:

admin.   blue-collar  entrepreneur     housemaid    management       retired self-employed      services       student 
technician    unemployed       unknown 

#### Marital:

divorced  married   single  unknown 

```{r dataset, include=TRUE}

df <- read.csv2("./bank-additional.csv")

###age
df$age <- cut(df$age, 
              breaks = c(0, 25, 45, 65, max(df$age)),
              labels = c("A", "B", "C", "D"))

###jobs
df %>% mutate(job = ifelse(job == "retired" | job == "unemployed" | job == "student" | job == "housemaid", "unemployed", job))
df %>% mutate(job = ifelse(job == "entrepeneur", "self-employed", job))

###education
df %>% mutate(education = ifelse(education, education == "basic.4y" | education == "basic.6y" | education == "basic.9y", "basic", education))
df %>% mutate(education = ifelse(education, education == "unknown", NA , education))

###duration
df <- cut(df$duration,
          breaks = c(0, 30, 300, max(df$duration)),
          labels = c("Baixa", "Mitja", "Alta"))

###pdays
df %>% mutate(pdays = ifelse(pdays, pdays == 999, NA , pdays))
```
