---
title: "Case Study"
author: "Daniel Villalobos"
date: "`r Sys.Date()`"
output:
  html_document: default
  toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Carrega inicial de les dades
```{r}
file_path = "/Users/danielvillalobostorrejon/Documents/Profe/ADEI/2022/segon_semestre/case_study/bank-additional-full.csv"
df = read.csv2(file_path, header = T)
```

```{r}
head(df)
```

### Mostra de les dades amb les que treballare
```{r}
set.seed(1)
n <- 5000
number_of_trues = as.integer(runif(1, min = 2400, max=2600))
```


```{r}
df_yes = df[df$y=="yes",]
df_yes = df_yes[sample(1:number_of_trues), ]

df_no = df[df$y=="no",]
df_no = df_no[sample(1:(n-number_of_trues)),]
df = rbind(df_yes, df_no)
```


### Análisis Exploratori

```{r}
summary(df)
str(df)
```


```{r}
hist(df$age)
```


```{r}
barplot(prop.table(table(df$job)))
```

```{r}
barplot(100*prop.table(table(df$marital)))

which(df$marital == "unknown")
```

```{r}
barplot(100*prop.table(table(df$education)))
```


```{r}
barplot(100*prop.table(table(df$housing)))
```

```{r}
barplot(100*prop.table(table(df$loan)))

```

```{r}

barplot(100*prop.table(table(df$contact)))
```


```{r}
barplot(100*prop.table(table(df$month)))

```

```{r}
barplot(100*prop.table(table(df$day_of_week)))

```

```{r}
hist(df$duration) #MALA PINTA

df[which(df$duration == 4918),]
```


```{r}
hist(df$campaign)

```

```{r}
hist(df$pdays) #ALTANTO 999 - DESDOBLAAAR! 

```

```{r}
hist(df$previous)

```

```{r}
barplot(table(df$poutcome))

```

```{r}
hist(as.numeric(df$emp.var.rate))
```

```{r}
table(df$emp.var.rate) #VARIACI? TREBALL TRIMESTRAL 

```

```{r}
table(df$cons.price.idx) #IPC MENSUAL

```

```{r}

table(df$cons.conf.idx) # INDEX CONFIAN?A CONSUMIDOR
```

```{r}

table(df$euribor3m) #EURIBOR A TRES MESOS PER DIA
```


```{r}
table(df$nr.employed) #TREBALLADOR PER TRIMESTRE
```



### Transformacions

```{r}
summary(df)
```

#### Factoritzar variables categoriques
```{r}
summary(df$job)
df$job <- as.factor(df$job)
summary(df$job)
```


```{r}
levels(df$education)
df$education <- as.factor(df$education)
levels(df$education)
```

#### Manera eficient de fer-ho
```{r}
df[sapply(df, is.character)] <- lapply(df[sapply(df, is.character)], 
                                       as.factor)
summary(df)
```

#### Agrupar categories

```{r}
df$education_grouped <- df$education
levels(df$education_grouped) <- c("basic", "basic","basic","high.school","illiterate", "professional.course", "university.degree", "unknown")
levels(df$education_grouped)
```

#### Factoritzar variables numériques
```{r}
summary(df$duration)
df$duration_cuted <- cut(df$duration, breaks=c(3,172,477.1,685,4200), include.lowest = T)
summary(df$duration_cuted)
```


### missings 
```{r}
df$marital[df$marital == 'unknown'] = NA
levels(df$marital)
summary(df$marital)

levels(df$marital)[levels(df$marital)=='unknown'] <- NA
summary(df$marital)
```

##### outliers
```{r}
boxplot(df$duration)
outliers <- boxplot.stats(df$duration)$out
out_ind <- which(df$duration %in% c(outliers))
df[out_ind,]$duration <- NA
summary(df$duration)
```

