---
title: "Entrega-2"
author: "Ivan Cala Mesa, Pau Bosch Ribalta"
date: "2023-03-28"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load Required Packages: to be increased over the course
options(contrasts=c("contr.treatment","contr.treatment"))

requiredPackages <- c("chemometrics","FactoMineR","car","knitr","missMDA")

package.check <- lapply(requiredPackages, FUN = function(x) {
  for (x in requiredPackages) {
    if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies  = TRUE)
    library(x, character.only = TRUE)
  }
  }
})
```

```{r}
load("./bank-additional-clean.RData")
```

## Listing out variables

```{r}
summary(df)

# List of variable names for the target variable
target_vars <- names(df$y)

# List of variable names for the discrete variables
discrete_vars <- names(Filter(is.factor, df))
discrete_vars = discrete_vars[discrete_vars != 'y']

# List of variable names for the continuous variables
continuous_vars <- names(Filter(is.numeric, df))

```

Con el objetivo de poder encuadrar la variable binaria 'Y' en una regresión logística, será necesario asumir que las observaciones son independientes entre sí. Esto significa que los valores de la variable objetivo "Y" de una observación no están relacionados o influenciados por los valores de otras observaciones.

```{r}
# División del conjunto de datos en muestra de trabajo y muestra de prueba
set.seed(123)  # Para reproducibilidad
sample_size <- floor(0.8 * nrow(df))  # Tamaño de muestra de trabajo (80%)
train_index <- sample(seq_len(nrow(df)), size = sample_size)  # Índices de muestra de trabajo

# Creación de la muestra de trabajo y muestra de prueba
train_data <- df[train_index, ]
test_data <- df[-train_index, ]
```

```{r}
# Modelo inicial con dos variables numéricas y factores significativos
model <- glm(y ~ age_num + duration + job + education + housing + loan + month,
             data = train_data, family = binomial)
summary(model)
vif(model)
marginalModelPlots(model)
```

```{r}
model1 <- glm(y ~ age_num + duration + education + housing + loan + month,
             data = train_data, family = binomial)
summary(model1)
vif(model1)
marginalModelPlots(model1)
residualPlots(model1)
```

```{r}
# Compute correlation coefficients between Y and other variables
#correlations <- cor(df[, -which(names(df) == "y")], df$y)

# Print correlation coefficients
#print(correlations)

```

```{r}
# Incorporar interacciones entre factores y una covariable
model2 <- glm(y ~ age_num * education + duration + housing + loan + month,
                          data = train_data, family = binomial)
summary(model2)
```

```{r}
# Incorporación de interacción entre factores
model3 <- glm(y ~ age_num * education + # factor and covariate
                              loan * month + # couple of factors
                              duration + 
                              housing,
                          data = train_data, family = binomial)
summary(model3)
```

```{r}
model4 <- glm(y ~ age_num * education + # factor and covariate
                  loan * month * housing + # couple of factors
                  duration,
                data = train_data, family = binomial)
summary(model4)
```

```{r}
# Crear una lista de los modelos
model_list <- list(model1, model2, model3, model4)

# Crear una lista de etiquetas para los modelos
model_labels <- c("Model 1", "Model 2", "Model 3", "Model 4")

# Crear un layout de múltiples gráficos en una sola figura
par(mfrow = c(2, 2))  # 2 filas y 2 columnas para 4 gráficos

# Realizar los plots para cada modelo
lapply(seq_along(model_list), function(i) {
  plot(model_list[[i]], which = 1, main = paste("Residuos de Pearson -", model_labels[i]))
  plot(model_list[[i]], which = 2, main = paste("Residuos de Desviación -", model_labels[i]))
})

```

```{r}


```

```{r}
# Predicción en la muestra de trabajo
train_pred <- predict(model_final, train_data, type = "response")
train_pred_class <- ifelse(train_pred > 0.5, "yes", "no")

# Matriz de confusión en la muestra de trabajo
train_actual <- train_data$y
train_confusion <- table(Actual = train_actual, Predicted = train_pred_class)
train_confusion

# Predicción en la muestra de prueba
test_pred <- predict(model_final, test_data, type = "response")
test_pred_class <- ifelse(test_pred > 0.5, "yes", "no")

# Matriz de confusión en la muestra de prueba
test_actual <- test_data$y
test_confusion <- table(Actual = test_actual, Predicted = test_pred_class)
test_confusion
```
